[package]
name = "durl-gui-dx"
version = "0.1.0"
authors = ["luyi <luyikk@126.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7", features = ["fullstack","router"] }
download-lib = { path = "../download-lib" }
tokio = { version = "1", features = ["full"] }
toml = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
dirs = "5"
rfd = "0.14"
open = "5"
ntex = { version = "3", features = ["tokio"] }
anyhow = "1"
dashmap = "6"
log = "0.4"
arboard = "3"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]

[build-dependencies]
winres = "0.1"
ico = "0.5"