/// Pre-computed CSS class strings for each theme mode.
/// Components read `ThemeClasses` via `use_context` and apply the classes directly.
#[derive(Debug, Clone, PartialEq)]
pub struct ThemeClasses {
    pub page_bg: &'static str,
    pub panel_bg: &'static str,
    pub sidebar_bg: &'static str,
    pub border: &'static str,
    pub divider: &'static str,
    pub accent: &'static str,
    pub accent_hover: &'static str,
    pub accent_light: &'static str,
    pub text_primary: &'static str,
    pub text_secondary: &'static str,
    pub text_muted: &'static str,
    pub hover_bg: &'static str,
    pub button_primary: &'static str,
    pub button_primary_hover: &'static str,
    pub button_text: &'static str,
    pub card_bg: &'static str,
    pub card_hover: &'static str,
    pub input_bg: &'static str,
    pub input_border: &'static str,
    pub badge_bg: &'static str,
    pub badge_text: &'static str,
    pub active_item_bg: &'static str,
    pub active_item_accent: &'static str,
    pub active_item_text: &'static str,
    pub scrollbar_thumb: &'static str,
    pub scrollbar_thumb_hover: &'static str,
    pub logo_gradient: &'static str,
    pub logo_text: &'static str,
}

pub const DARK: ThemeClasses = ThemeClasses {
    page_bg: "bg-[#0b0d14]",
    panel_bg: "bg-[#0d1018]",
    sidebar_bg: "bg-[#11141c]",
    border: "border-[#1e2430]",
    divider: "bg-[#1e2430]",
    accent: "text-[#6C5CE7]",
    accent_hover: "hover:text-[#7C6CF7]",
    accent_light: "bg-[#6C5CE7]/10",
    text_primary: "text-slate-200",
    text_secondary: "text-slate-400",
    text_muted: "text-slate-700",
    hover_bg: "hover:bg-[#1a1e28]",
    button_primary: "bg-[#6C5CE7] hover:bg-[#7C6CF7] active:bg-[#5C4CD7]",
    button_primary_hover: "bg-[#7C6CF7]",
    button_text: "text-white",
    card_bg: "bg-[#141820]",
    card_hover: "hover:bg-[#181c26]",
    input_bg: "bg-[#0d1018]",
    input_border: "border-[#1e2430] focus:border-[#6C5CE7]/50",
    badge_bg: "bg-[#0b0d14]",
    badge_text: "text-slate-500",
    active_item_bg: "bg-[#1a1e28]",
    active_item_accent: "border-l-[#6C5CE7]",
    active_item_text: "text-slate-200",
    scrollbar_thumb: "#2a3040",
    scrollbar_thumb_hover: "#3a4050",
    logo_gradient: "from-[#6C5CE7] to-purple-500",
    logo_text: "text-white",
};

pub const LIGHT: ThemeClasses = ThemeClasses {
    page_bg: "bg-[#f5f5f7]",
    panel_bg: "bg-[#fafafa]",
    sidebar_bg: "bg-[#f0f0f2]",
    border: "border-[#e0e0e6]",
    divider: "bg-[#e0e0e6]",
    accent: "text-[#6C5CE7]",
    accent_hover: "hover:text-[#7C6CF7]",
    accent_light: "bg-[#6C5CE7]/8",
    text_primary: "text-slate-800",
    text_secondary: "text-slate-600",
    text_muted: "text-slate-400",
    hover_bg: "hover:bg-[#e8e8ee]",
    button_primary: "bg-[#6C5CE7] hover:bg-[#7C6CF7] active:bg-[#5C4CD7]",
    button_primary_hover: "bg-[#7C6CF7]",
    button_text: "text-white",
    card_bg: "bg-white",
    card_hover: "hover:bg-[#fafafe]",
    input_bg: "bg-white",
    input_border: "border-[#d0d0d8] focus:border-[#6C5CE7]/50",
    badge_bg: "bg-[#f0f0f2]",
    badge_text: "text-slate-600",
    active_item_bg: "bg-[#e8e8f0]",
    active_item_accent: "border-l-[#6C5CE7]",
    active_item_text: "text-slate-800",
    scrollbar_thumb: "#c0c0c8",
    scrollbar_thumb_hover: "#a0a0a8",
    logo_gradient: "from-[#6C5CE7] to-purple-500",
    logo_text: "text-white",
};
